# Generated by Django 3.2 on 2021-05-25 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volleyballschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainings_qty', models.PositiveSmallIntegerField(verbose_name='Количество тренировок')),
                ('validity', models.PositiveSmallIntegerField(verbose_name='Срок действия(дней)')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('start_date', models.DateField(blank=True, default=None, verbose_name='Дата начала действия')),
                ('end_date', models.DateField(blank=True, default=None, verbose_name='Дата окончания действия')),
                ('trainings', models.ManyToManyField(blank=True, to='volleyballschool.Training', verbose_name='Тренировки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Абонемент пользователя',
                'verbose_name_plural': 'Абонементы пользователей',
            },
        ),
    ]
