# Generated by Django 3.2 on 2021-05-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyballschool', '0003_onetimetraining_subscriptionsamples2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos_of_courts/', verbose_name='Фото')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('metro', models.CharField(max_length=50, verbose_name='Станция метро')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
    ]
