# Generated by Django 3.2 on 2021-05-06 14:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyballschool', '0004_courts3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('active', models.BooleanField(verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.AlterField(
            model_name='onetimetraining',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Цена(руб.)'),
        ),
        migrations.AlterField(
            model_name='subscriptionsamples',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Стоимость(руб.)'),
        ),
        migrations.AlterField(
            model_name='subscriptionsamples',
            name='validity',
            field=models.PositiveSmallIntegerField(verbose_name='Срок действия(дней)'),
        ),
    ]
