# Generated by Django 3.2 on 2021-06-04 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyballschool', '0004_auto_20210530_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='learners',
            field=models.ManyToManyField(blank=True, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Посетители'),
        ),
    ]
