# Generated by Django 3.2 on 2021-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyballschool', '0005_auto_20210506_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='short_description',
            field=models.TextField(default=None, max_length=400, verbose_name='Краткое описание статьи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True, verbose_name='Slug( URL )'),
            preserve_default=False,
        ),
    ]
